#!/bin/bash
# cron job to archive sensor data

export PATH=$PATH:/usr/local/myscripts

	TARGET_IP=$DEV
	
	LOCAL_DIR=/media/Logs/sensor-data
	REMOTE_DIR=/media/data/sensors
	LOG_DIR=/media/Logs/sensor-data

	LOG_FILE=maint.log
	ARCHIVE_FILE=master.dat
	TEMP_FILE=td.dat
	SENSOR_FILE=sensor.dat

	printf "\n*** sensor archive started " >> $LOCAL_DIR/$LOG_FILE 2>&1
	date +"%T %D"  >> $LOCAL_DIR/$LOG_FILE 2>&1
	printf "TARGET_IP=$TARGET_IP\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "LOCAL_DIR=$LOCAL_DIR\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "REMOTE_DIR=$REMOTE_DIR\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "LOG_DIR=$LOG_DIR\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "LOG_FILE=$LOG_FILE\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "ARCHIVE_FILE=$ARCHIVE_FILE\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "TEMP_FILE=$TEMP_FILE\n" >> $LOCAL_DIR/$LOG_FILE 2>&1
	# printf "SENSOR_FILE=$SENSOR_FILE\n" >> $LOCAL_DIR/$LOG_FILE 2>&1

# rename remote sensor log file file
rename=$(ssh root@$TARGET_IP "mv -v $REMOTE_DIR/$SENSOR_FILE $REMOTE_DIR/$TEMP_FILE")
printf "$rename" >> $LOCAL_DIR/$LOG_FILE 2>&1
# move temp file to local
	rsync -avz  root@$TARGET_IP:$REMOTE_DIR/$TEMP_FILE $LOCAL_DIR/$TEMP_FILE >> $LOCAL_DIR/$LOG_FILE 2>&1		
	printf "$? returned from rsync\n" >> $LOCAL_DIR/$LOG_FILE 2>&1															
	if [ $? == 0 ] 	# test return code
		then 			
			remove=$(ssh root@$TARGET_IP "rm -v $REMOTE_DIR/$TEMP_FILE")	# delete remote temp file
			printf "$remove" >> $LOCAL_DIR/$LOG_FILE 2>&1										
		else
			printf "rsync error >$?<, script aborted"  >> $LOCAL_DIR/$LOG_FILE 2>&1
			exit 1
	fi				
# append local temp file to local master
	cat $LOCAL_DIR/$TEMP_FILE >> $LOCAL_DIR/$ARCHIVE_FILE >> $LOCAL_DIR/$LOG_FILE 2>&1
	if [ $? == 0 ] 	# test return code
		then	
			printf "$REMOTE_DIR/$TEMP_FILE appended to $REMOTE_DIR/$ARCHIVE_FILE" >> $LOCAL_DIR/$LOG_FILE 2>&1
		else
			printf "cat error >$?<, script aborted" >> $LOCAL_DIR/$LOG_FILE 2>&1
			exit 1
	fi

	printf "*** sensor archive completed " >> $LOCAL_DIR/$LOG_FILE 2>&1
	date +"%T %D"  >> $LOCAL_DIR/$LOG_FILE 2>&1

