#!/bin/bash

printf "\n load_bone 0.4.0\n"
target_IP=192.168.254.75

#	target_IP := 192.168.256.34
bone_BIN_DIR=/usr/local/sbin

# set directories
CURRENT_OS=$(uname)
if [ $CURRENT_OS == "Linux" ]
then 
	program_DIR_PREFIX=/home/mam1/Git/Pcon-TNG
else 
	program_DIR_PREFIX=/Users/mam1/Git/Pcon-TNG
fi

# move the bins to the bone
printf "\n *** rsync -> $program_DIR_PREFIX/bin/ root@$target_IP:$bone_BIN_DIR\n"
rsync -azv      $program_DIR_PREFIX/bin/ root@$target_IP:$bone_BIN_DIR

# move shell scripts to the bone
printf "\n *** rsync -> $program_DIR_PREFIX/script_lib/Bone/ root@$target_IP:$bone_BIN_DIR" 
rsync -azv      $program_DIR_PREFIX/script_lib/Bone/ root@$target_IP:$bone_BIN_DIR

# fix permissions
$(ssh root@$target_IP chown root:root $bone_BIN_DIR)	# change owner
$(ssh root@$target_IP chmod 4755 $bone_BIN_DIR)		# open access