#!/bin/bash
# append the sensor log file to master file
# and clear sensor log file

echo -e "\n\rgrabit 0.1.3\n\r"

CURRENT_OS=$(uname)
echo -n "operating system is "
echo $CURRENT_OS

if [ $CURRENT_OS == "Linux" ]
then
	echo -e "\rappending active sensor log to master log\r"
	rsync  -azv --append --progress root@192.168.254.34:/media/CGI-sensor-log/sensor.dat /media/Raid/SensorMaster/temp_sensor.dat 
	echo -n $?
	echo -e " returned from rsync\n\r"

	cat /media/Raid/SensorMaster/temp_sensor.dat >> '/media/Raid/SensorMaster/master.log'
	ssh root@192.168.254.34 'rm /media/CGI-sensor-log/sensor.dat'
	rm /media/Raid/SensorMaster/temp_sensor.dat
else
	echo -e "can not grab sensor log from OS X\n\r"
fi
