#!/bin/bash
# append the sensor log file to master file
# clear sensor log file
# push summerized sensor data ot dropbox

APP="pullit"
VER="0.1.6"
DATE="$(date +'%m/%d/%Y')"
TIME="$(date +'%r')"


CURRENT_OS=$(uname)
if [ $CURRENT_OS == "Linux" ]
then
# append working sensor from the bone to the master log and erase working log
	echo -e "\n*********************************************************************" >> '/media/Raid/sensor logs/pullit.log'
	echo -e $APP $VER "run at" $TIME "on" $DATE >> '/media/Raid/sensor logs/pullit.log'
	echo -e "\rappending active sensor log to master log\r" >> '/media/Raid/sensor logs/pullit.log'
	echo -e $(rsync  -azv root@192.168.254.34:/media/sensor.dat '/media/Raid/sensor logs/temp_sensor.dat') >> '/media/Raid/sensor logs/pullit.log' 
	echo -n $? >> '/media/Raid/sensor logs/pullit.log'
	echo -e " returned from rsync" >> '/media/Raid/sensor logs/pullit.log'
	cat '/media/Raid/sensor logs/temp_sensor.dat' >> '/media/Raid/sensor logs/master.dat'
	echo -e "erase working sensor log file on bone"
	echo -e $(ssh root@192.168.254.34 'rm /media/sensor.dat') >> '/media/Raid/sensor logs/pullit.log'

# process the master log
	DATE="$(date +'%m/%d/%Y')"
	TIME="$(date +'%r')"
	rm '/media/Raid/sensor logs/temp_sensor.dat'
	echo -e "run at" $TIME "on" $DATE >> '/media/Raid/sensor logs/temp_sensor.dat'
	# echo -e $(/home/mam1/Git/Pcon-TNG/Mint/process-master/process) >> '/media/Raid/sensor logs/temp_sensor.dat
	cat '/media/Raid/sensor logs/temp_sensor.dat' >> '/media/Raid/sensor logs/pullit.log'

# push summery data to dropbox
	echo $(/home/mam1/Git/Dropbox-Uploader/dropbox_uploader.sh upload '/media/Raid/sensor logs/temp_sensor.dat' sensors) >> '/media/Raid/sensor logs/pullit.log'

else
# running on OS X don't do anthing
	echo -e "can not grab sensor log from OS X\n\r"
fi
