#!/bin/bash
# push the routers external IP address to dropbox

APP="push_ip"
VER="0.1.0"
DATE="$(date +'%d/%m/%Y')"
TIME="$(date +'%r')" 
IP="$(curl -s ipinfo.io/ip)"

#check for internet connection
wget -q --spider http://google.com

if [ $? -eq 0 ]; then
    STATUS="Online"
else
    STATUS="Offline"
fi

echo -e "\n\r"$APP $VER "run at" $TIME "on" $DATE >> /media/Raid/SensorMaster/exip.log
if [[ $STATUS == "Offline" ]]; then
	echo  -e "internet is not available - restarting Mint Box" >> /media/Raid/SensorMaster/exip.log
	init 6		# restart
else
	echo -e "VPN is connected" >> /media/Raid/SensorMaster/exip.log
	echo -e "external IP address" $IP >> /media/Raid/SensorMaster/exip.log
	rm /media/Raid/SensorMaster/exip.dat
	echo -e "\n\r"$APP $VER "run at" $TIME "on" $DATE >> /media/Raid/SensorMaster/exip.dat
	echo -e "VPN status" $(expressvpn status) >> /media/Raid/SensorMaster/exip.dat
	echo -e "external IP address" $IP >> /media/Raid/SensorMaster/exip.dat
	echo $(/home/mam1/Git/Dropbox-Uploader/dropbox_uploader.sh upload /media/Raid/SensorMaster/exip.dat current_ip) >> /media/Raid/SensorMaster/exip.log
fi