ifndef t
$(error target for make not set)
endif

target_MACHINE:=$t
code_DIRECTORY:=/home/mam1/Git/Pcon-TNG/test_daemons
system_BINARIES:=/home/mam1/Git/Pcon-TNG/bin
program_NAME:=Dcon
daemon_PROCESS:=yes
bone_BIN_DIR:=/usr/local/sbin

include ~/Git/Pcon-TNG/BBB/mastermake/Makefile


