
/* cmd_defs version info */
#define _MAJOR_VERSION    10
#define _MINOR_VERSION    4
#define _MINOR_REVISION   0

#include <sys/sem.h>
#include <sys/ipc.h>
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <unistd.h>		//sleep
#include <stdint.h>		//uint_8, uint_16, uint_32, etc.
#include <ctype.h> 		//isalnum, tolower
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include "shared.h"


/* command definitions */
char    *keyword_defs[_CMD_STATES][_CMD_TOKENS] = {{
	// state 0
	/*  0 temp        */    "",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "",
	/*  7 cancel      */    "",
	/*  8 replace     */    "",
	/*  9 sedit       */    "maintain sensor information",
	/* 10 delete      */    "",
	/* 11 */    "",
	/* 12 */    "",
	/* 13 */    "",
	/* 14 clear       */    "",
	/* 15 */    "",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "",
	/* 18 */    "",
	/* 19 */    "",
	/* 20 */    "",
	/* 21  save        */    "",
	/* 22 */    "",
	/* 23 */    "",
	/* 24  load        */    "edit schedule template library",
	/* 25 set          */    "",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"set channel number (0 - 15) for next action (i.e, 0 on)",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{ 	// state 1
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 */    "set channel mode to time",
	/* 17 */    "set channel control mode to time and sensor",
	/* 18 */    "set channel control mode to cycle",
	/* 19 */    "",
	/* 20 */    "",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"channel name enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 2
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 3
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 4
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "replace system schedule table with working schedule table",
	/*  9 sedit       */    "",
	/* 10 delete      */    "delete a saved template or schedule table",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "clear the schedule buffer",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "save the working schedule or the working schedule table",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 load        */    "load a template into the schedule buffer or \n\r                 load the working schedule table with a saved schedule table",
	/* 25 set         */    "load a schedule into working schedule table",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"start editing a schedule record, schedule record hour",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 5
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 6
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 7
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 8
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 9
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 10
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	//	state 11
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 12
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{	// state 13
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"hour",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{// state 21
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"sensor id",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1*           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 sedit       */    "",
	/* 10 delete      */    "the system schedule with the contents of the edit buffer",
	/* 11 active      */    "edit system schedule",
	/* 12 on          */    "turn channel on, set channel control mode to manual",
	/* 13 off         */    "turn channel off, set channel control mode to manual",
	/* 14 clear       */    "t",
	/* 15 status      */    "display status of each chanel",
	/* 16 time        */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24  load        */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 grab        */    "move current sensor data log to the master file and erase data log",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 INT         */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token",
	/* 38 slist       */    "display list of active sensors and their current values "
}};


char *cmd_def(int state, int token_number){

	// printf("cmd_def called with token %i and state %i\r\n", token_number, state);

	return keyword_defs[state][token_number];
}