#include "shared.h"

char *cmd_def(int token_number, int state){

/* command definitions */
char    *keyword_defs[_CMD_STATES][_CMD_TOKENS] = {{
	// state 0
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{ 	// state 1
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "set channel mode to time",
	/* 17 */    "set channel control mode to time and sensor",
	/* 18 */    "set channel control mode to cycle",
	/* 19 */    "",
	/* 20 */    "",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"channel name enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 2
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 3
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 4
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 5
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 6
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 */    "temperature",
	/*  1 */    "",
	/*  2 */    "",
	/*  3 */    "maintain system schedule",
	/*  4 */    "display all commands valid in current state",
	/*  5 */    "set the real time clock",
	/*  6 */    "send a ping to the C3",
	/*  7 */    "build time date structure to set PCF8563 real tim clock",
	/*  8 */    "set PCF8563",
	/*  9 */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14 */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21 */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34 */	"",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
}};

return keyword_defs[state][token_number];
}