#include <sys/sem.h>
#include <sys/ipc.h>
#include <sys/types.h>
#include <errno.h>
#include <stdio.h>
#include <unistd.h>		//sleep
#include <stdint.h>		//uint_8, uint_16, uint_32, etc.
#include <ctype.h> 		//isalnum, tolower
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include "shared.h"


/* command definitions */
char    *keyword_defs[_CMD_STATES][_CMD_TOKENS] = {{
	// state 0
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"channel number (0 - 15)",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{ 	// state 1
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "set channel mode to time",
	/* 17 */    "set channel control mode to time and sensor",
	/* 18 */    "set channel control mode to cycle",
	/* 19 */    "",
	/* 20 */    "",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"channel name enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 2
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 3
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 4
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "replace system schedule table with working schedule table",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "clear the schedule buffer",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "save a schedule template or an entire schedule",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "load the active schedule into the working schedule table",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"schedule record hour",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 5
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{	// state 6
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{// state 21
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"sensor id",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1*           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
},
{
	/*  0 temp        */    "temperature",
	/*  1 *           */    "",
	/*  2 humid       */    "",
	/*  3 schedule    */    "maintain system schedule",
	/*  4 ?           */    "display all commands valid in current state",
	/*  5 clock       */    "set the real time clock",
	/*  6 yes         */    "send a ping to the C3",
	/*  7 cancel      */    "build time date structure to set PCF8563 real tim clock",
	/*  8 replace     */    "set PCF8563",
	/*  9 edit        */    "",
	/* 10 */    "the system schedule with the contents of the edit buffer",
	/* 11 */    "edit system schedule",
	/* 12 */    "turn channel on, set channel control mode to manual",
	/* 13 */    "turn channel off, set channel control mode to manual",
	/* 14  clear       */    "t",
	/* 15 */    "display status of each chanel",
	/* 16 */    "display the time and date from the real time clock",
	/* 17 */    "display status for all channels",
	/* 18 */    "set channel control mode to time",
	/* 19 */    "set channel control mode to time and sensor",
	/* 20 */    "set channel control mode to cycle",
	/* 21  save       */    "startup",
	/* 22 */    "display",
	/* 23 */    "save schedule template",
	/* 24 */    "edit schedule template library",
	/* 25 set         */    "channel",
	/* 26 */    "load",
	/* 27 */    "unrecognized command",
	/* 28 */    "display all valid commands",
	/* 29 */    "terminate Pcon",
	/* 30 */    "end function",
	/* 31 */    "back up one state",
	/* 32 */    "display system data",
	/* 33 */    "display debug data",
	/* 34  disp_tlib  */	"display contents of template library",
	/* 35 */	"integer",
	/* 36 */	"alpha numeric string enclosed in quotes",
	/* 37 */	"any unrecognized token"
}};


char *cmd_def(int state, int token_number){

	// printf("cmd_def called with token %i and state %i\r\n", token_number, state);

	return keyword_defs[state][token_number];
}