#!/bin/bash
#
#	bload - move binaries from development machine to a bone
#
# set directories
target_MACHINE=$1
program_DIR_PREFIX=$2
bone_BIN_DIR=$3

# move the bins to the bone
printf "  copying binaries to device at $target_MACHINE"
printf "\n *** rsync -> $program_DIR_PREFIX/bin/ root@$target_MACHINE:$bone_BIN_DIR\n"
rsync -azv      $program_DIR_PREFIX/bin/ root@$target_MACHINE:$bone_BIN_DIR
printf "\n"

# fix permissions
ssh root@$target_MACHINE chown root:root $bone_BIN_DIR/*	# change owner
ssh root@$target_MACHINE chmod 777 $bone_BIN_DIR/*		# open access