#!/bin/bash
#
#	login to beaglebone on local network
#
if [ $# == 0 ]
	then
		printf "enter host name > "
		read answr
		host_name=$answr
	else
		host_name=$1
fi
case  $host_name  in
    bone1)       
	    host_ip=192.168.254.204;;
    bone2)
	    host_ip=192.168.254.205;; 
    bone3)       
	    host_ip=192.168.254.206;;
    bone-img)
	    host_ip=192.168.254.207;;           
    *) 
    	printf "unrecognized host name <$host_name>\n" 
    	printf "valid host names are:\n    bone1\n    bone2\n    bone3\n    bone-img\n\n"
    	exit 1            
esac 

printf "\n  host name $host_name\n"
printf "  host address $host_ip\n"

ssh root@$host_ip