#!/bin/bash
#
#	move scripts from ../script_lib/Bone to a bone

target_ip=''
if [ $# == 0 ]
    then
        printf "usage 'bload <prod|dev|last section of ip adress>'\n"
        exit
    else
        case "$1" in
            'prod' | '77')
            target_ip=192.168.254.77
        ;;
            'dev' | '34' | 'dev')
            target_ip=192.168.254.34
        ;;
        esac
fi

if [ -z $target_ip ]
    then
        printf "invalid parameter\nscript aborted\n"
    exit
fi

bone_BIN_DIR=/usr/local/sbin

# set directories
CURRENT_OS=$(uname)
if [ $CURRENT_OS == "Linux" ]
	then 
		program_DIR_PREFIX=/home/mam1/Git/Pcon-TNG
	else 
		program_DIR_PREFIX=/Users/mam1/Git/Pcon-TNG
fi

# move shell scripts to the bone
printf "  copying scripts to device at $target_ip\n"
printf "\n *** rsync -> $program_DIR_PREFIX/script_lib/Bone/ root@$target_ip:$bone_BIN_DIR\n" 
rsync -azv      $program_DIR_PREFIX/script_lib/Bone/ root@$target_ip:$bone_BIN_DIR
printf "\n"

# fix permissions
ssh root@$target_ip chown root:root $bone_BIN_DIR/*	# change owner
ssh root@$target_ip chmod 777 $bone_BIN_DIR/*		# open access