#!/bin/bash
#
#	scriptload
#


if [ $# == 0 ]
	then
		printf "\n    bone1=192.168.254.204\n"
		printf 	 "    bone2=192.168.254.205\n"
		printf   "    bone3=192.168.254.206\n\n"
		printf "  enter target > "
		read answr
		if [ "$answr" == "bone1" ] 
		then
			target_IP=192.168.254.204
		else
			if [ "$answr" == "bone2" ]
				then
					target_IP=192.168.254.205
				else
					if [ "$answr" == "bone3" ]
					then
						target_IP=192.168.254.206
					else
						printf "must select bone1, bone2 or bone3\nscript aborted\n"
						exit 1
					fi
				fi
		fi
fi

case "$1" in
'bone1' | '192.168.254.204')
target_IP=192.168.254.204
;;
'bone2' | '192.168.254.205' | 'dev')
target_IP=192.168.254.205
;;
'bone3' | '192.168.254.206' | 'prod')
target_IP=192.168.254.206
;;
esac

if [ -z $target_IP]
	then
		printf "invalid parameter\nscript aborted\n"
	exit
fi




bone_BIN_DIR=/usr/local/sbin

# set directories
CURRENT_OS=$(uname)
if [ $CURRENT_OS == "Linux" ]
then 
	program_DIR_PREFIX=/home/mam1/Git/Pcon-TNG
else 
	program_DIR_PREFIX=/Users/mam1/Git/Pcon-TNG
fi

# move shell scripts to the bone
printf "  copying scripts to device at $target_IP\n"
printf "\n *** rsync -> $program_DIR_PREFIX/script_lib/Bone/ root@$target_IP:$bone_BIN_DIR\n" 
rsync -azv      $program_DIR_PREFIX/script_lib/Bone/ root@$target_IP:$bone_BIN_DIR
printf "\n"

# fix permissions
ssh root@$target_IP chown root:root $bone_BIN_DIR/*	# change owner
ssh root@$target_IP chmod 777 $bone_BIN_DIR/*		# open access