//
// automatically generated by spin2cpp v1.03 on Sun Nov 17 14:43:27 2013
// C:\Users\Dave\Desktop\test999\spin2cpp.exe --ccode test.spin 
//

#ifndef fdsSpin_Class_Defined__
#define fdsSpin_Class_Defined__

#include <stdint.h>


typedef struct fdsSpin {
  char dummy__;
} fdsSpin;

  int32_t	fdsSpin_Start(int32_t Rxpin, int32_t Txpin, int32_t Mode, int32_t Baudrate);
  int32_t	fdsSpin_Stop(void);
  int32_t	fdsSpin_Rxflush(void);
  int32_t	fdsSpin_Rxcheck(void);
  int32_t	fdsSpin_Rxtime(int32_t Ms);
  int32_t	fdsSpin_Rx(void);
  int32_t	fdsSpin_Tx(int32_t Txbyte);
  int32_t	fdsSpin_Str(int32_t Stringptr);
  int32_t	fdsSpin_Dec(int32_t Value);
  int32_t	fdsSpin_Hex(int32_t Value, int32_t Digits);
  int32_t	fdsSpin_Bin(int32_t Value, int32_t Digits);
#endif
