//
// automatically generated by spin2cpp v1.03 on Sun Nov 17 14:43:27 2013
// C:\Users\Dave\Desktop\test999\spin2cpp.exe --ccode test.spin 
//

#ifndef testSpin_Class_Defined__
#define testSpin_Class_Defined__

#include <stdint.h>
#include "fds.h"


typedef struct testSpin {
  char dummy__;
} testSpin;

  int32_t	testSpin_Main(void);
#endif
