ifndef t
$(error target for make not set)
endif

working_DIRECTORY:=UI 
program_NAME:=Pcon 
target_MACHINE:=$t
program_DIR_PREFIX := /home/mam1/Git/Pcon-TNG
bone_BIN_DIR := /usr/local/sbin

include ~/Git/Pcon-TNG/BBB/mastermake/Makefile