#!/bin/bash
#####################################
# 
#		start Dcon
#
#####################################

# PATH=/sbin:/usr/sbin:/bin:/usr/bin
# DESC="Programmable controller deamon"
# NAME=Dcon
# DAEMON=/usr/local/sbin/$NAME
# DAEMON_ARGS=""
# PIDFILE=/run/$NAME.pid

#	checking for active processes - kill if found
plist=$(pidof /usr/local/sbin/Dcon)
if [ "$plist" != "" ] 
	then
		kill $plist
fi

# start daemon 
echo -e "\n*****************************************\nstarting scheduler daemon" >> /home/mam1/logs/daemon.log
sudo Dcon >> /home/mam1/logs/daemon.log

exit 0