#!/bin/bash
	echo -e "\n\rgrabit 0.1.3\n\r"
	echo -n "operating system is "
	echo $(uname)
	if(($(uname)=="Linux"))
	then
		echo -e "\rappending active sensor log to master log\r"
		rsync  -azv --append --progress /media/CGI-sensor-log/temp_sensor.dat mam1@192.168.254.70:/media/Raid/SensorMaster/master.log
		echo -n $?
		echo -e " returned from rsync\n\r"
		
		# rm /media/CGI-sensor-log/sensor.dat
	else
		echo -e "can not grab sensor log from OS X\n\r"
	fi
