#!/bin/bash
# start up script for 16 channel controller


echo " 
********************************
  starting setup script v 0.0
********************************

  checking for active processes
"
list=$(pidof /usr/local/sbin/Dcon)
if [ "$list" != "" ]; then
	echo "there is an instance of Dcon active pid "$(list)
	echo "killing it"
	kill $list
else
	echo "there are no instances of Dcon active"
fi

list=$(pidof /usr/local/sbin/Pcon)
echo $list
if [ "$list" != "" ]; then
	echo "there is an instance of Pcon active pid "$(list)
	echo "killing it"
	kill $list
else
	echo "there are no instances of Pcon active"
fi

Dcon > /home/Pcon-data/Dcon.log &
Pcon

exit 0