#!/bin/bash
# start up script for 16 channel controller
stty cooked		# switch to buffered iput
stty echo		# turn on terminal echo
echo "reinitializing terminal io"

echo " 
********************************
  starting setup script v 0.0
********************************

"
echo "checking for active processes"
list=$(pidof /usr/local/sbin/Dcon)
if [ "$list" != "" ]; then
	echo "there is an instance of Dcon active pid "$(list)
	echo "killing it"
	kill $list
else
	echo "there are no instances of Dcon active"
fi

list=$(pidof /usr/local/sbin/Pcon)
if [ "$list" != "" ]; then
	echo "there is an instance of Pcon active pid "$(list)
	echo "killing it"
	kill $list
else
	echo "there are no instances of Pcon active"
fi
echo "starting daemon"
sleep 10
Dcon > /home/Pcon-data/Dcon.log &
Pcon

exit 0